Ad login
Artificial-Collective/cookiecutter-streamlit-heroku pull request #3
Opened 2023-05-05 11:14 UTC by setseed42

2023-05-05 11:29 UTC, e-larsson requested changes
Looks good! 🙌 Very clean, and neat. Just had some questions

2023-05-05 11:29 UTC, e-larsson commented on {{ cookiecutter.repo_name }}/src/security.py
> +        st.stop()
Is this rendered as text? Would it be easy to switch to a Login button?

2023-05-05 11:29 UTC, e-larsson commented on {{ cookiecutter.repo_name }}/src/security.py
> +    AUTHORITY = f'https://login.microsoftonline.com/{TENANT_ID}'
If we want to run GSuite instead, what would need to be changed? (Let's not prepare too much for that case right now, I'm just interested)

2023-05-05 11:29 UTC, e-larsson commented on {{ cookiecutter.repo_name }}/.github/workflows/ci-cd.yaml
> +        python-version: 3.9
Why not Python 3.11?

2023-05-08 09:10 UTC, setseed42 commented on {{ cookiecutter.repo_name }}/.github/workflows/ci-cd.yaml
> +        python-version: 3.9
Fixed

2023-05-08 09:12 UTC, merged